public: false
type: "docs"
category: "reference and outreach"
tags:
  - "digitization"
title: "Digitization Guide"
description: "Digitization practices and procedures for the RAC staff"
pages:
  - ["Digitization Guide", "index"]
